### PR TITLE
Added missing 'import numpy as np' statements to code examples

### PR DESCRIPTION
**Pull request by erikmannerfelt**
Found by @adehecq

### CODE REVIEW

**Review by adehecq — COMMENTED** [review]
Are the associated python codes (the source of the figures) in the GitHub repo, or somewhere else?

**Comment by erikmannerfelt** [comment]
They are in the documentation: `docs/source/comparison.py` and can be downloaded from https://xdem.readthedocs.io as I assumed you did.

**Comment by erikmannerfelt** [comment]
Is this okay to merge?

**Comment by adehecq** [comment]
Yes!

**Pull request merged**
