### PR TITLE
Fix issue with NaNs masks in Coreg methods

### PR DESCRIPTION
**Pull request by adehecq**
This is a fix to #237.
During coreg.apply, a resampling is needed. When NaNs exist in the input DEMs, the NaNs also propagate and must be handled carefully. Currently, such resampling is done at 3 different places, and NaNs are not always caught properly.
This PR tries to fix this issue.

I also fixed a small issue in BlockwiseCoreg. Errors during fitting were caught, but not during apply.

### CODE REVIEW

**Comment by adehecq** [comment]
Note that BlockwiseCoreg is not very reliable with large gaps, but the current fix improved it a bit. See figure of elevation difference after Blockwise coregistration (See attached script inspired from [test_blockwise_coreg_large_gaps](https://github.com/GlacioHack/xdem/blob/edde09b1e53701f2825b7cacf51d280646171fef/tests/test_coreg.py#L489)): [test_blockwise.txt](https://github.com/GlacioHack/xdem/files/7569255/test_blockwise.txt)

**Before the PR**
Figure_1

**After the PR**
Figure_2



The underlying NuthKaab method should probably be improved to be more robust with few points.

**Comment by adehecq** [comment]
Finally, this is another indication that Coreg methods should be thoroughly tested for datasets with large gaps (#140).

**Comment by rhugonnet** [comment]
Thanks for tackling this! It's good to have all these fixes incorporated right away.

I agree, we'll have to work on a testing scheme for outlier robustness! This can probably be done in the future by simulating data gaps/NaNs, which will also be super useful if we want to write a paper comparing the performance of `Coreg` methods and their robustness :smile: !

**Review by rhugonnet — APPROVED** [review]
Looks good!

**Pull request merged**
