### PR TITLE
Improve test suite to pass and add CI

### PR DESCRIPTION
**Pull request by erikmannerfelt**
I've made some corrections to make the tests work better than before. There are still some issues, and 2/37 still fail for me. @rhugonnet, I was hoping you could tell me what's up? It's the `DEM.set_vref()` test that fails with:

```
ValueError: Grid not found in /home/erik/.local/share/conda/xdem/lib/python3.8/site-packages/pyproj/proj_dir/share/proj: check if proj-data is installed via conda-forge, the pyproj.datadir, and that you are using a grid available at https://github.com/OSGeo/PROJ-data
```
when trying to set the vref to `'is_lmi_Icegeoid_ISN93.tif'` at:
https://github.com/GlacioHack/xdem/blob/64f348b6318aaa6313707772f99426294bfa6e38/tests/test_dem.py#L129

and a `Proj error` at:
https://github.com/GlacioHack/xdem/blob/64f348b6318aaa6313707772f99426294bfa6e38/tests/test_dem.py#L148

I have the latest `proj-data` installed...

Looking at the test execution time, I wonder if something  can be done about the `test_spstats.py` times, @rhugonnet? A test call of 294 s is quite long!
```
293.64s call     tests/test_spstats.py::TestVariogram::test_empirical_fit_variogram_running                                     
52.71s call     tests/test_spstats.py::TestPatchesMethod::test_patches_method                                                   
41.79s call     tests/test_coreg.py::TestCoregClass::test_pipeline                                                              
30.25s call     tests/test_coreg.py::TestCoreg::test_icp_pdal                                                                   
25.27s call     tests/test_coreg.py::TestCoregClass::test_icp_opencv                                                            
19.86s call     tests/test_coreg.py::test_only_paths                                                                            
19.51s call     tests/test_coreg.py::TestCoreg::test_amaury                                                                     
10.87s call     tests/test_ddem.py::TestdDEM::test_local_hypso                                                                  
8.27s call     tests/test_coreg.py::TestCoreg::test_icp_opencv                                                                  
8.26s call     tests/test_coreg.py::TestCoreg::test_amaury_high_degree                                                          
6.72s call     tests/test_coreg.py::TestCoregClass::test_subsample                                                              
3.95s call     tests/test_coreg.py::TestCoregClass::test_deramping
3.88s call     tests/test_demcollection.py::TestDEMCollection::test_init
2.03s call     tests/test_coreg.py::TestCoreg::test_raster_mask
1.84s call     tests/test_coreg.py::TestCoregClass::test_nuth_kaab
1.49s call     tests/test_coreg.py::TestCoreg::test_deramping
0.88s call     tests/test_ddem.py::TestdDEM::test_regional_hypso 
0.15s call     tests/test_spstats.py::TestVariogram::test_multirange_fit_performance
0.07s call     tests/test_demcollection.py::TestDEMCollection::test_ddem_interpolation
0.05s call     tests/test_dem.py::TestDEM::test_to_vref
0.04s call     tests/test_dem.py::TestDEM::test_init
0.04s call     tests/test_spatial_tools.py::test_dem_subtraction 
0.04s call     tests/test_spatial_tools.py::test_merge_rasters
0.04s call     tests/test_dem.py::TestDEM::test_copy
0.03s call     tests/test_ddem.py::TestdDEM::test_filled_data
0.02s call     tests/test_coreg.py::TestCoregClass::test_bias
0.02s call     tests/test_volume.py::TestLocalHypsometric::test_ddem_bin_methods
0.02s call     tests/test_ddem.py::TestdDEM::test_copy
0.02s call     tests/test_spstats.py::TestVariogram::test_neff_estimation
0.01s call     tests/test_dem.py::TestDEM::test_set_vref
0.01s call     tests/test_volume.py::TestLocalHypsometric::test_area_calculation
0.01s call     tests/test_volume.py::TestLocalHypsometric::test_bin_ddem
0.01s call     tests/test_coreg.py::TestCoregClass::test_coreg_add
0.01s call     tests/test_volume.py::TestLocalHypsometric::test_interpolate_ddem_bins
```

I also disabled plotting by default, to not require manual input for the test suite to run.

### CODE REVIEW

**Comment by erikmannerfelt** [comment]
I finally found a fix for my proj-related issue! `proj` could not find `proj-data` after installing it with conda. Using `pyproj.datadir.append_data_dir()` did not work for some reason. The only way I found to work was to create symbolic links:
```bash
ln -s "$(conda clean -d -a 2&>/dev/null | head -n1 | sed 's/Cache location: //g')"/proj-data*/share/proj/* $CONDA_PREFIX/lib/python*/site-packages/pyproj/proj_dir/share/proj/
```
I guess this could be implemented in build scripts, as the script above should work on all UNIX-based systems. @rhugonnet, do you have an alternative approach to fix this?

**Comment by rhugonnet** [comment]
> I guess this could be implemented in build scripts, as the script above should work on all UNIX-based systems. @rhugonnet, do you have an alternative approach to fix this?

Not really any alternative, no. Sorry!
Everything works fine for me after building the environment from scratch with the .yml file (using conda/mamba). I wonder what could be the cause of the issue on your side. :thinking: 

I guess that now with proj-data working, the 2 test issues you had should be passing? I never had any issue on my side with the test on vertical referencing, and made sure everything was passing.

For the length of the tests, I agree (I actually mentioned it when I pushed the original PR). The cause is the default value of `nsamp=10000` in `xdem.spstats.sample_multirange_empirical_variogram`. Which is better for good performance, but too long for testing. 
On lines 46, 49 and 53 of `test_spstats`, you should add `nsamp=1000` in the function calls to shorten the time by a factor of >10.

**Comment by erikmannerfelt** [comment]
@rhugonnet , it's not just my computer. When I tried to work on CI, it failed there as well. @adehecq also had the same issues, right?

I passed `nsamp=1000` to the functions you said and it takes 209.4s now. Not a huge improvement!

**Comment by erikmannerfelt** [comment]
Now I get all tests to pass! I've set pytest to skip `tests/test_spstats.py::TestVariogram::test_empirical_fit_variogram_running` until we figure out a faster way to run it.

There is still a warning somewhere in `spstats.py`. I'll see if I can find where it originates:
```
========================================================== test session starts ===========================================================
platform linux -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/erik/Projects/ETH/GlacioHack/xdem
plugins: xdist-2.2.1, forked-1.3.0
collected 37 items                                                                                                                       

tests/test_coreg.py ssssssss.......                                                                                                [ 40%]
tests/test_ddem.py .....                                                                                                           [ 54%]
tests/test_dem.py ....                                                                                                             [ 64%]
tests/test_demcollection.py ...                                                                                                    [ 72%]
tests/test_spatial_tools.py ..                                                                                                     [ 78%]
tests/test_spstats.py s...                                                                                                         [ 89%]
tests/test_volume.py ....                                                                                                          [100%]

============================================================ warnings summary ============================================================
tests/test_spstats.py::TestPatchesMethod::test_patches_method
  /home/erik/.local/share/conda/xdem/lib/python3.8/site-packages/numpy/lib/function_base.py:3636: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
    part.partition(kth)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================== 28 passed, 9 skipped, 1 warning in 159.95s (0:02:39) =========================================

```

**Comment by erikmannerfelt** [comment]
I found and fixed the warnings!

**Comment by rhugonnet** [comment]
I wanted to check what was taking so long in the test_variogram, but my geoutils

> I passed `nsamp=1000` to the functions you said and it takes 209.4s now. Not a huge improvement!

Testing on my side (took a bit of time to rebase geoutils + redownload datasets for remote xdem!), I think part of it might be coming from the function call now line 84 that also requires a `nsamp=1000`.
Then, I don't how CI deals with multi-core processing, but I assume it probably only has one and multi-processing gets queued sequentially. So we could simplify the function call line 87 to `nrun=5`, `nproc=2`.

**Comment by erikmannerfelt** [comment]
@rhugonnet, now it works in 14 seconds!!

**Comment by erikmannerfelt** [comment]
Update on the proj issues I had. They're magically gone! 

I just reinstalled my whole environment, and now things seem to be in order. Could also be with the upgrade to `proj==8.0.0` which was made unavailable due to the `environment.yml` (but which I have fixed).

**Comment by erikmannerfelt** [comment]
I found that the following test only succeeds about 86% of the times it is run:
https://github.com/GlacioHack/xdem/blob/8e3f06e794a4ff866194baec8e993bb9522f821b/tests/test_spstats.py#L102
I presume that the uncertainty comes from the randomness of the method.

I found this out by running `tests/test_spstats.py` 140 times and it failed 36 times.

Therefore, I set its errors as warnings, and we can fix it to be more reliable later.

**Comment by rhugonnet** [comment]
Nice catch! Yes that is not surprising, the convergence for such a sum of variogram can be quite hard to constrain on poor, random sampling. It was probably failing a lot less using 10,000 samples before, but then it was taking too long.

Now you know the dilemma I had when writing this test!

**Comment by erikmannerfelt** [comment]
As you can see, I got CI to work! It takes around 10 minutes (6 minutes to build environment, 4 minutes for pytest). I think that's okay, and we don't need to set the "tests must pass to merge" rule yet. This will just mean that the build checks are good indicators of whether things are looking okay or not.

Most important of all (I'm joking), we get this nice badge!
[build](https://github.com/erikmannerfelt/xdem/actions/workflows/python-package.yml)

I also fixed an issue I had in [glacier_lengths](https://github.com/erikmannerfelt/glacier_lengths) regarding pypi uploading. This fix should make it work (but it still haven't been triggered since we don't yet do versioning).

Solves #19.

**Review by rhugonnet — APPROVED** [review]
Looks good!

**Comment by adehecq** [comment]
Nice job !!!!
(Sorry for the slow reaction)

**Pull request merged**
