### PR TITLE
Added barebones documentation

### PR DESCRIPTION
**Pull request by erikmannerfelt**

### CODE REVIEW

**Comment by erikmannerfelt** [comment]
I am currently testing readthedocs using my own fork. I'll merge this when it seems to work and I have confirmation from any of you @rhugonnet  or @adehecq.

**Comment by rhugonnet** [comment]
Wow it looks hard to make ReadTheDocs happy :wink: !

**Comment by erikmannerfelt** [comment]
Sorry, I should have marked it as a draft! It almost works now. Latest problem is I found that we use python>=3.8 syntax, and the readthedocs python version is 3.7... Working on a fix now.

**Comment by erikmannerfelt** [comment]
It's working! Muhahahaha only took a part of my soul to get working.

[See the result here](https://xdem-erikm.readthedocs.io/en/latest/index.html). If you don't find anything catastrophically wrong, I'll merge this.

**Comment by erikmannerfelt** [comment]
Note that this needed a fix so that `xdem` can run in python=3.7. It couldn't before!

**Review by adehecq — APPROVED** [review]
Looking good! Well done!

**Comment by erikmannerfelt** [comment]
Cool! I'll maybe add some more text and then I'll merge

**Comment by rhugonnet** [comment]
Yes, looks good :). Resolves #20

**Pull request merged**
