### PR TITLE
Fix history to remove blobs above 3 MiB

### PR DESCRIPTION
**Pull request by erikmannerfelt**
I used [bfg-repo-cleaner](https://github.com/rtyley/bfg-repo-cleaner) to remove all blobs above 3 MiB.

```bash
bfg --strip-blobs-bigger-than 3M
# I have no idea what the script below does but the script above told me to do it!
git reflog expire --expire=now --all && git gc --prune=now --aggressive

```

### CODE REVIEW

**Comment by adehecq** [comment]
This is a bit of a mystery what this tool does and I'm concerned we could break things. Have you checked the git log after runnign this command?

**Comment by erikmannerfelt** [comment]
I agree that this is scary haha! The history is the same as the main branch on my fork (which I stupidly submitted the merge_rasters PR on...):

```
commit fd670e4fa0489531854a5411d62d3d3f131d3e80 (HEAD -> fix_history, origin/main, origin/fix_history, origin/HEAD, main)
Author: Erik Holmlund <erik-holmlund@hotmail.com>
Date:   Wed Mar 10 10:32:36 2021 +0100

    Added function to merge rasters using any callable (mean, median, sum etc.)
    
    
    Former-commit-id: 4ed6d81fb93c51896a845b8abd3e20f9f5d31b64

commit b6cfa7b74555d649e73c0b28021c4796e9a33b9a (upstream/main)
Merge: 4972ed1 cdf6273
Author: Romain Hugonnet <romain.hugonnet@gmail.com>
Date:   Wed Mar 10 10:06:42 2021 +0100

    Merge pull request #34 from erikmannerfelt/main
    
    Move examples to one place: a separate examples directory + ICP coreg improvements
    
    Former-commit-id: 0182b822172a63232943cda5b4baea95fea73938

commit cdf62732c63fa3c748f713d4ee17089f0600e8c3
Author: Erik Holmlund <erik-holmlund@hotmail.com>
Date:   Tue Mar 9 15:20:28 2021 +0100

    Improved nodata handling and made sure input DEMs are (converted to) floats
    
    
    Former-commit-id: 98520543222db4829d0e35a0af726264b42e599b

commit 38ea614873254addb7fb668c8e9b960218b543f1
Author: Erik Holmlund <erik-holmlund@hotmail.com>
Date:   Tue Mar 9 15:18:44 2021 +0100

    Added opencv as an optional dependency
    
    
    Former-commit-id: 3f937a2ef07233e3c1c97f90e0cb1d9a3c20e1ed

commit 206de2b0b57c0dbf68ba3ac277bbec1a38ffdc53
Merge: 124e9c2 4972ed1
Author: Erik Holmlund <erik-holmlund@hotmail.com>
Date:   Tue Mar 9 14:57:10 2021 +0100

    Merged pull and fixed conflicts with environment
    
    
    Former-commit-id: 9c722b465412c3ea00b327237295ef50689956fd

commit 124e9c2c8322c68582618681767f57fee536fbae
Author: Erik Holmlund <erik-holmlund@hotmail.com>
Date:   Tue Mar 9 14:39:08 2021 +0100

    Modified PDAL ICP implementation to handle memory better. Added opencv ICP implementation which is much faster. Set the opencv ICP approach as the default 'icp' method.
    
    
    Former-commit-id: 66d20f676fa0780a3e6b8287b614b7033d80ef23

```

**Comment by adehecq** [comment]
I mean, what does the log look like for the commits where the data was added/modified?

**Comment by erikmannerfelt** [comment]
This rewrites the entire history to exclude the blobs.

The merging method would decide how it would look in the xdem/main history

**Comment by erikmannerfelt** [comment]
Maybe I should emphasise that this has not been a lot of work for me, so we can reject the PR and then let a git-wizard (anyone know of any??) do this operation for us.

**Comment by rhugonnet** [comment]
> Maybe I should emphasise that this has not been a lot of work for me, so we can reject the PR and then let a git-wizard (anyone know of any??) do this operation for us.

Don't know about any git wizard :mage: , unfortunately!

**Comment by adehecq** [comment]
I just compared the history between your branch and the master, and it seems like the changes are pretty transparent. The files are gone forever from the git history, which is a good thing.
I think we can try to merge.

**Review by adehecq — APPROVED** [review]

**Comment by erikmannerfelt** [comment]
I just fixed the merge conflicts, so it's ready when you are!

**Pull request merged**
