### PR TITLE
Enable building the doc in offline formats

### PR DESCRIPTION
**Pull request by adehecq**
This is a one line PR with a minor change to readthedocs config file.
Solves #362.

### CODE REVIEW

**Review by rhugonnet — APPROVED** [review]
Great!
I didn't know about this. Is it going to be downloadable directly from the readthedocs website, without changing anything in `doc/source/conf.py`?

**Comment by rhugonnet** [comment]
Btw, you can do the same in GeoUtils :wink:

**Comment by rhugonnet** [comment]
Merging before making a release

**Comment by adehecq** [comment]
Yes, it' easy to download from the doc. Simply click on the "Read The Docs" button on the bottom left and you will see the different download options 😄. The link for the pdf version is https://xdem.readthedocs.io/_/downloads/en/latest/pdf/

**Pull request merged**
