### PR TITLE
Move documentation to `sphinx-book-theme` and `myst`

### LINKED ISSUE #295: Increase width of doc
Currently, the width of the documentation is too narrow compared to our standard code width (120 characters). This means the code does not appear all at once and one needs to scroll horizontally.
There are some solutions [here](https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs) that can be tested.
The comment by Yahya Yahyaoui seems the simplest, so worth testing.

### LINKED ISSUE #296: Make xdem convertible to binder
It would be great to create a binder from xdem repository directly. To do that, I see two issues:
1. Once the Binder created, starting a console and running `import xdem` raises "ModuleNotFoundError: No module named 'xdem'". Something must be changed to xdem's configuration probably
2. All our examples are python scripts, that are not so nice to work with on Jupyter Lab. If [jupytext](https://github.com/mwouts/jupytext/blob/main/README.md#sphinx-gallery-scripts) is added as a dependency, the jupyterlab will be able to open any script as a notebook. With jupytext, it works but the notebooks look quite ugly (see screenshot below), so we need to improve that.

image

To reproduce:
1. Go https://mybinder.org/ and use URL GlacioHack/xdem to start the Binder.
2. Install jupytext with `conda install -c conda-forge jupytext`, then start `jupyter notebook` and open any of xdem's example scripts

### PR DESCRIPTION
**Pull request by rhugonnet**
This PR updates xDEM's documentation format and theme, finishes fixes with the new GeoUtils behaviour (#341) and finishes the setup of Binder.

It largely mirrors https://github.com/GlacioHack/geoutils/pull/351 on all documentation aspects, see that PR for reference.

In short:
- No content is changed, simply the theme to `sphinx-book-theme` and the format to `myst`,
- Configuration of sphinx is refined,
- Setup for readthedocs are improved,
- The codes in `/docs/source/code` used to populate some pages have been moved directly into the documentation as `myst-nb` code-cells,
- Any documentation page with code can now be launched as a notebook in Binder.

A couple notable addition of this PR:
- It refactors `xdem/docs/` into `xdem/doc/` for consistency with GeoUtils, and other packages,
- It adds `"dollarmath"` to `myst_enable_extensions` in the documentation configuration to represent equations,
- It rewrites the `README` and `CONTRIBUTING` in the same style as for GeoUtils, with several new badges.

## Issues solved

This PR:
- Resolves #295,
- Resolves #296 

## Old text

> 
> **Here's an example of the new documentation, especially the updated "About xDEM" page with some functionalities of `sphinx-book-theme` such as margin admonitions or sidenotes:**
> https://xdem-rhugonnet.readthedocs.io/en/doc_booktheme/about_xdem.html
> 
> What improvements we'd be looking at:
> 
> - The look is cleaner, with a width/font ratio slightly larger to avoid long pages, which partially solves #295;
> - The theme comes with a lot of practical options for documentation: direct link to open an issue from the doc, downloading any page in RST/PDF, and launching an interactive code with a Binder from the doc, which would solve #296;
> - The theme support margin sidenotes, figures, or admonitions, which are kept on the side for a cleaner read on wide screens, but collapse in-line on narrower screens (e.g., mobile), which further solves #295 of the readthedocs theme.
> - The theme relies on MyST markdown (see https://myst-parser.readthedocs.io/en/latest/), which allows for a bit more that classic markdown or reStructuredText. It only parses `.md` files differently, leaving our current `.rst` files interpreted in HTML the same. We can easily transition all files using `rst2myst` (see https://rst-to-myst.readthedocs.io/en/latest/).
> - The theme has a good, growing community behind it. Recently, the parent `pydata-sphinx-theme` added support for a "dark-theme toggle" functionality, which will soon be inherited by the `sphinx-book-theme` as well, and save our eyes while working on the docs! :smile:

### CODE REVIEW

**Comment by adehecq** [comment]
Great initiative ! A few comments:
- It will take me some time to get used to the new theme... but it does not mean we should not change it 🙃 
- Indeed, the theme is very white/bright. I liked that the previous one was a bit darker. Can we already try the dark mode? Or can we set a different color for the side columns?
- The side notes are a cool feature, but we should not overuse them. The "About xdem" page you made is nice, but there is a lot of information in an unordered way, so I find it a bit more difficult to read.
- Very importantly, this PR will not solve #296. It will just make it easier to link it to Binder, but we still need to setup the binder configuration.

**Comment by rhugonnet** [comment]
Answers:

- Dark mode will come in a few months normally, they are working on it but it's mostly inheritance from the parent theme so not too much work,
- Yes the "About xDEM" page is just to give an example (although it's not too much info for me, but at the upper limit).

**Comment by rhugonnet** [comment]
Merging now as no documentation content is changed and the final fixes are required to make tests pass.

**Comment by adehecq** [comment]
Nice to have both documentations updated now ! 🥳 

> * The theme comes with a lot of practical options for documentation: direct link to open an issue from the doc, downloading any page in RST/PDF, and launching an interactive code with a Binder from the doc, which would solve https://github.com/GlacioHack/xdem/issues/296;

Maybe I missed something, but I couldn't find a button to start a binder from one of the examples (e.g. [this one](https://xdem.readthedocs.io/en/latest/advanced_examples/plot_slope_methods.html#sphx-glr-advanced-examples-plot-slope-methods-py)). 
Can you explain how to start a binder?

**Comment by rhugonnet** [comment]
Unfortunately, sphinx-gallery + Binder does not work with readthedocs (last paragraph of the section at the link in previous comment):

> It is not currently possible to host notebooks generated by Sphinx-Gallery with readthedocs.org, as RTD does not provide you with a GitHub repository you could link Binder to. If you’d like to use readthedocs with Sphinx-Gallery and Binder links, you should independently build your documentation and host it on a GitHub branch as well as building it with readthedocs.

Looking deeper, it looks like they are thinking of making the link easier in `sphinx-gallery`, but no PR on this is ongoing, so it might take a while (for instance: https://github.com/sphinx-gallery/sphinx-gallery/issues/603).

Looks like it is possible to somehow circumvent the problem in the meantime: https://stanczakdominik.github.io/posts/simple-binder-usage-with-sphinx-gallery-through-jupytext/

**Comment by rhugonnet** [comment]
@adehecq @erikmannerfelt @atedstone You probably received the Readthedocs email saying that `build.image` is deprecated and needs to be changed to `build.os` in `readthedocs.yaml`, and that this impacts our Readthedocs projects (details here: https://blog.readthedocs.com/use-build-os-config/).
Thankfully, the changes to the new syntax were already made in April in geoutils/xdem when I updated the `readthedocs.yaml` to use `mamba-forge`, so it's all good!
We'll keep receiving Readthedocs emails until the final phase of migration mid-October in any case.

**Comment by adehecq** [comment]
Thanks @rhugonnet for looking into the Binder issue. It seems quite complicated indeed and probably not worth the huge effort. Another option is to have a separate repository with some demo files, like I did for the winter school in Nepal: https://github.com/GlacioHack/xdem-demo. Each project can be a different branch.

And thanks for looking into the readthedocs warning!

**Comment by rhugonnet** [comment]
This makes me think: for binder, we cannot rely on the current system anymore, they have lost most of their servers. I'll open an issue.

**Pull request merged**
